services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /home/jaspertech/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=America/New_York

  music-assistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/jaspertech/music-assistant:/data
    environment:
      - TZ=America/New_York

  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WHISPER_MODEL=base-int8
      - WHISPER_LANG=en
      - WHISPER_VAD_FILTER=true
      - WHISPER_BEAM_SIZE=5
    volumes:
      - /home/jaspertech/whisper:/config
    ports:
      - 10300:10300

  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PIPER_VOICE=en_US-lessac-medium
    volumes:
      - /home/jaspertech/piper:/config
    ports:
      - 10200:10200
